project:
  type: website
  resources: 
    - "assets/challenges_images/"
    - "assets/images/"
    - "assets/fonts/"
    - "assets/scripts/"
    - ".htaccess"
website:
  title: "Christian Gebhard"
  description: "Data Visualization"
  navbar:
    left: 
      - text: "blog"
        href: posts.html
      - text: "dataviz"
        href: challenges.html
      - text: "projects"
        href: projects.html
    right:
      - text: "about"
        href: about.html
      - icon: github
        href: https://github.com/nucleic-acid
      - icon: twitter
        href: https://twitter.com/c_gebhard
      - icon: mastodon
        href: https://scicomm.xyz/@basepair
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-8792-565X
      - icon: rss
        href: posts.xml
  site-url: https://jollydata.blog
  twitter-card: true
  open-graph: true
  favicon: assets/images/logo_favicon.png
  image: assets/images/logo_dynamic_hero.png
  cookie-consent: 
    policy-url: datenschutz.html
  page-footer: 
    left: Christian A. Gebhard {{< fa regular copyright >}} 2022<br>made with {{< fa heart >}}, {{< fa brands r-project >}}  and [quarto](https://quarto.org)
    right: 
      - text: Impressum
        href: impressum.html
      - text: Privacy / Datenschutz
        href: datenschutz.html
  comments: 
    giscus:
      repo: nucleic-acid/quarto-blog
highlight-style: arrow
format:
  html:
    theme: 
      light: [litera, jollydata.scss]
      dark: [superhero, jollydata.scss]
    code-link: true
    code-fold: true
    code-tools: 
      toggle: true
      source: false
    



