---
page-layout: custom
comments: false
---

<link rel="me" href="https://vis.social/@basepair" />
<link rel="me" href="https://genomic.social/@basepair" />
<link rel="me" href="https://scicomm.xyz/@basepair" />


::: {.grid}
::: {.g-col-10 .g-start-2 .g-col-sm-10 .g-start-sm-2 .g-col-md-10 .g-start-md-2 .g-col-lg-5 .g-start-lg-2}

::: {.welcome-title}
Hello there and welcome!
:::

::: {.welcome-message}
My name is Christian and I have a passion for clear and appealing data visualizations. 

Go ahead and check out my previous visualizations or have a look at my blog. You can read more about me [here](about.html).

Do you want me to work on your data or need a data visualization training? [Let's connect](contact.html)!
:::

:::

::: {.g-col-0 .g-start-col-0 .g-col-lg-5 .welcome-hero}


:::

:::

<br><br>

::: {.grid}


::: {.g-col-10 .g-start-2 .g-col-md-4 .g-start-md-3}
<div class="card mb-2">
<div class="card-body">
<h5 class="card-title">Data Visualizations</h5>
<p class="card-text">A collection of charts, infographics and dataviz designs created for previous projects & community-driven data challenges.</p>
<a href="challenges.html" class="btn btn-primary stretched-link">Browse</a>
</div>
</div>
:::

::: {.g-col-10 .g-start-2 .g-col-md-4}
<div class="card mb-2">
<div class="card-body">
<h5 class="card-title">Jolly Data Blog</h5>
<p class="card-text">A blog on the exploration of open data using open source tools,
such {{< fa brands r-project >}} and {{< fa brands python >}}. I share here, what I learned on my way.</p>
<a href="posts.html" class="btn btn-info stretched-link">Start reading</a>
</div>
</div>
:::

::: {.g-col-10 .g-start-2 .g-col-md-4 .g-start-md-3}
<div class="card mb-2">
<div class="card-body">
<h5 class="card-title">Projects</h5>
<p class="card-text">A collection of ongoing data-endeavors, programming projects and {{< fa brands r-project >}} packages.</p>
<a href="projects.html" class="btn btn-danger stretched-link">Take me there</a>
</div>
</div>
:::

::: {.g-col-10 .g-start-2 .g-col-md-4}
<div class="card mb-2">
<div class="card-body">
<h5 class="card-title">Contact</h5>
<p class="card-text">Want me for a project or training?
You can reach me on different channels or directly schedule an exploratory call.</p>
<a href="contact.html" class="btn btn-success stretched-link">Connect</a>
</div>
</div>
:::


:::

::: {.welcome-message}




:::
